### ISSUE TITLE
Re-register markerclustererplus in bower

### ISSUE THREAD

**Issue by mahnunchik** [mahnunchik/markerclustererplus#15]
Hi @andreychernih 

What do you think about to register this repository under the canonical name `markerclustererplus`?

As I understand it, now it is occupied by your fork:
```bash
$ bower search markerclustererplus
Search results:
    gmaps-markerclusterer-plus git://github.com/mahnunchik/markerclustererplus.git
    markerclustererplus git://github.com/andreychernih/markerclustererplus.git
```

**Comment by andreychernih** [comment]
Yeah, sorry about that. I've just de-registered it, feel free to take over this name.

**Comment by mahnunchik** [comment]
It's all right. Thank you!
