### ISSUE TITLE
Cluster click event is not triggered on full screen mobile map

### ISSUE THREAD

**Issue by renjithkj** [mahnunchik/markerclustererplus#34]
When google map is rendered on full screen, on a mobile device the cluster click events don't trigger.

**Comment by ragmha** [comment]
I have managed a quick fix using the specific release version of google maps API

add v=3 as params see example below:
``
https://maps.googleapis.com/maps/api/js?v=3&key=<API_KEY>
``

for more info read this:  https://developers.google.com/maps/documentation/javascript/releases#332

**Comment by renjithkj** [comment]
That works. Thanks. :)
